
defaults:
  - _self_

_name_ : CustomizedModel
_target_: models.CustomizedModel.CustomizedModel
input_channels: 1
d_model: 128
oa_mlp_d_model : 128
oo_mlp_d_model : 128

patch_len : 1
is_frozen : 0

model_root_path : checkpoints/CustomizedModel
model_save_name : 

is_load_pretrain_model : 0
