defaults:
  - model : PSSM
  - data : AF
  - _self_

hydra : 
  mode : MULTIRUN
  searchpath:
    - file://config


task : ${data.task}
seed : 10086
input_length: ${data.data.input_length}
dataset_name : ${data.data.dataset_name}
dataset_path : ${data.data.dataset_path}
dataset_save : ${data.data.dataset_save}
dataset_balance: ${data.data.dataset_balance}
criterion: ${data.data.criterion}
predict_length : ${data.data.predict_length}

is_load_finetune_model : 0
is_frozen: ${model.is_frozen}
model_name: ${model._name_}
model_root_path: ${model.model_root_path}
model_save_name: ${model.model_save_name}
d_model: ${model.d_model}
oa_mlp_d_model : ${model.oa_mlp_d_model}
oo_mlp_d_model : ${model.oo_mlp_d_model}
is_load_pretrain_model: ${model.is_load_pretrain_model}
patch_len: ${model.patch_len}

hid_mlp: ${data.head.hid_mlp}

ffd_model_name: FFDModel
ffd_model_root_path: checkpoints/FFDModel
ffd_model_save_name: FFDModel.pth
ffd_patch_len: 50
ffd_batch_size: 4096

is_save_result: 1
is_finetune: 1

device: cuda:0
epochs: 100
learning_rate: 1e-5
batch_size: 1024
monitor_iter: 10
save_epoch: 20
finetune_rate: 0.5
sub_dataset: 1

use_wandb: 1
project_name: ECG-Benchmark
username: tang_zhi_jiang-ucas
